### ISSUE TITLE
Getting WARNING:requests.packages.urllib3.contrib.pyopenssl when using python requests

### ISSUE THREAD

**Issue by scottbarron1313** [shazow/urllib3#1319]
Hi, 
I'm using python's requests module to make some API calls. Starting about a week ago, I get this warning message related to urllib3 every time I make a call:

WARNING:requests.packages.urllib3.contrib.pyopenssl:A problem was encountered with the certificate that prevented urllib3 from finding the SubjectAlternativeName field. This can affect certificate validation. The error was Codepoint U+002A at position 1 of u'*' not allowed
/Library/Python/2.7/site-packages/requests/packages/urllib3/connection.py:337: SubjectAltNameWarning: Certificate for plasma-ticket.geo.apple.com has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning

Module versions:
urllib3==1.10.4
requests==2.12.4
pyOpenSSL==0.15.1

An example of a requests call (I'm using a few different ones, but they all follow this same format):

response = requests.post(<url>, data = json.dumps(data), headers = self.headers)
response_json = json.loads(response.content)

One note (that seems strange to me) is that I have logging set up using python's logging module, and instead of these messages showing up in my .log file, they only show in my terminal window. Don't know if that's useful at all.

Thanks

**Comment by haikuginger** [comment]
@scottbarron1313, can you test with the most recent `requests`, `urllib3`, and `pyOpenSSL`? We fixed a bug similar to this in our own package a while back, but it seems like this might be coming from lower down. I took a quick peek at the `cryptography` source code (which PyOpenSSL depends on) and it seems like they might have fixed it as well, but I'm not positive.

**Comment by scottbarron1313** [comment]
That seems to have done it! Thanks for the help!

**Comment by jcalabro** [comment]
@haikuginger

Hi there, I'm also seeing a similar issue. Upgrading to latest hasn't helped me unfortunately. From `pip list`:

pyOpenSSL (17.5.0)
requests (2.18.1)
urllib3 (1.22)

I'm running python 3.6 in this case.

Here is some sample code that reproduces the it:

```python
import requests

def get_cert_path(extension):
    return '<path_to_cert>/<name_of_cert>.' + extension

response = requests.get(
    'https://<url>',
    verify=get_cert_path('pem'),
    cert=(
        get_cert_path('cert'),
        get_cert_path('key')
    )
)

print(response.status_code)
```

With all the cert paths and urls in place, I get:

```
/Users/<user>/.pyenv/versions/uplift/lib/python3.6/site-packages/urllib3/connection.py:344: SubjectAltNameWarning: Certificate for <url> has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
200
```

Any advice you can offer would be much appreciated. Thanks! 😄

**Comment by SethMichaelLarson** [comment]
Hey @jcalabro, thanks for reporting this! Can you open a separate issue with your exact Python version and the contents of `python -m pip freeze` for your minimal-reproducing case?

**Comment by nebul4ck** [comment]
Hi, in my case it seems is not resolved:

**Code**:
send_post = requests.post(runner_command, verify=buanaCA, headers=headers, data=data, auth=basic_auth)

**Ouput**:
/usr/lib/python2.7/dist-packages/requests/packages/urllib3/connection.py:340: SubjectAltNameWarning: Certificate for buanarepo-lab.wtelecom.es has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning

Modules:
    Resquests:
Package: python-requests
Version: 2.13.0-1
Priority: optional

    pyOpenSSL:
Name: pyOpenSSL
Version: 0.15.1
Summary: Python wrapper module around the OpenSSL library

    urllib3:
Name: urllib3
Version: 1.20
Summary: HTTP library with thread-safe connection pooling, file post, and more.

Why?

Thanks in advanced

**Comment by SethMichaelLarson** [comment]
@nebul4ck Have you read #1351? If the certificate doesn't provide the field then we're unable to verify against it. Otherwise issue #497 has a lot of discussion about potential issues that may trigger this warning. If neither of those resolve the issue you can open up a new issue.

**Comment by nebul4ck** [comment]
Hi, in my case it seems is not resolved:

**Code**:
send_post = requests.post(runner_command, verify=buanaCA, headers=headers, data=data, auth=basic_auth)

**Ouput**:
/usr/lib/python2.7/dist-packages/requests/packages/urllib3/connection.py:340: SubjectAltNameWarning: Certificate for buanarepo-lab.wtelecom.es has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning

Modules:
    Resquests:
Package: python-requests
Version: 2.13.0-1
Priority: optional

    pyOpenSSL:
Name: pyOpenSSL
Version: 0.15.1
Summary: Python wrapper module around the OpenSSL library

    urllib3:
Name: urllib3
Version: 1.20
Summary: HTTP library with thread-safe connection pooling, file post, and more.

Why?

Thanks in advanced

**Comment by sigmavirus24** [comment]
This issue and the warning above are two separate warnings. This issue is about a failure to properly handle the text in the subjectAltName by underlying libraries. The warnings you're seeing are related to the #497 which means that the certificate of the website you're talking to is old, antiquated, improperly configured, and may in the future stop workin
